from __future__ import annotations

DOMAIN = "entity_distance"

CONF_ENTITY_A = "entity_a"
CONF_ENTITY_B = "entity_b"
CONF_ENTRY_THRESHOLD_M = "entry_threshold_m"
CONF_EXIT_THRESHOLD_M = "exit_threshold_m"
CONF_DEBOUNCE_S = "debounce_s"
CONF_MAX_ACCURACY_M = "max_accuracy_m"
CONF_MAX_SPEED_KMH = "max_speed_kmh"
CONF_RESYNC_SILENCE_S = "resync_silence_s"
CONF_RESYNC_HOLD_S = "resync_hold_s"
CONF_MIN_UPDATES_RELIABLE = "min_updates_reliable"
CONF_UPDATES_WINDOW_S = "updates_window_s"
CONF_REQUIRE_RELIABLE = "require_reliable"

DEFAULT_ENTRY_THRESHOLD_M = 200
DEFAULT_EXIT_THRESHOLD_M = 500
DEFAULT_DEBOUNCE_S = 10
DEFAULT_MAX_ACCURACY_M = 100
DEFAULT_MAX_SPEED_KMH = 1000
DEFAULT_RESYNC_SILENCE_S = 600
DEFAULT_RESYNC_HOLD_S = 60
DEFAULT_MIN_UPDATES_RELIABLE = 3
DEFAULT_UPDATES_WINDOW_S = 300
DEFAULT_REQUIRE_RELIABLE = False

DIRECTION_APPROACHING = "approaching"
DIRECTION_DIVERGING = "diverging"
DIRECTION_STATIONARY = "stationary"
DIRECTIONS = [DIRECTION_APPROACHING, DIRECTION_DIVERGING, DIRECTION_STATIONARY]

BUCKET_VERY_NEAR = "very_near"
BUCKET_NEAR = "near"
BUCKET_MID = "mid"
BUCKET_FAR = "far"
BUCKET_VERY_FAR = "very_far"
BUCKETS = [BUCKET_VERY_NEAR, BUCKET_NEAR, BUCKET_MID, BUCKET_FAR, BUCKET_VERY_FAR]

BUCKET_THRESHOLDS = {
    BUCKET_VERY_NEAR: 50,
    BUCKET_NEAR: 200,
    BUCKET_MID: 1000,
    BUCKET_FAR: 5000,
}

STATIONARY_THRESHOLD_M = 5.0
UPDATES_FREQUENCY_WINDOW_S = 300

EVENT_ENTER = f"{DOMAIN}_enter"
EVENT_LEAVE = f"{DOMAIN}_leave"
EVENT_UPDATE = f"{DOMAIN}_update"
EVENT_ENTER_UNRELIABLE = f"{DOMAIN}_enter_unreliable"
