from __future__ import annotations

DOMAIN = "entity_distance"

CONF_ENTITIES = "entities"  # list of entity IDs for group tracking
MAX_GROUP_ENTITIES = 5
CONF_PROXIMITY_ZONE = "proximity_zone"
CONF_DEBOUNCE_S = "debounce_s"
CONF_MAX_ACCURACY_M = "max_accuracy_m"
CONF_MAX_SPEED_KMH = "max_speed_kmh"
CONF_RESYNC_SILENCE_S = "resync_silence_s"
CONF_RESYNC_HOLD_S = "resync_hold_s"
CONF_GRACE_WINDOW_S = "grace_window_s"
CONF_MIN_UPDATES_RELIABLE = "min_updates_reliable"
CONF_UPDATES_WINDOW_S = "updates_window_s"
CONF_REQUIRE_RELIABLE = "require_reliable"
CONF_ZONE_VERY_NEAR_M = "zone_very_near_m"
CONF_ZONE_NEAR_M = "zone_near_m"
CONF_ZONE_MID_M = "zone_mid_m"
CONF_ZONE_FAR_M = "zone_far_m"

DEFAULT_DEBOUNCE_S = 0
DEFAULT_MAX_ACCURACY_M = 300
DEFAULT_MAX_SPEED_KMH = 1000
DEFAULT_RESYNC_SILENCE_S = 600
DEFAULT_RESYNC_HOLD_S = 60
DEFAULT_GRACE_WINDOW_S = 900
DEFAULT_MIN_UPDATES_RELIABLE = 3
DEFAULT_UPDATES_WINDOW_S = 1800
DEFAULT_REQUIRE_RELIABLE = False
DEFAULT_PROXIMITY_ZONE = "very_near"
DEFAULT_ZONE_VERY_NEAR_M = 200
DEFAULT_ZONE_NEAR_M = 1000
DEFAULT_ZONE_MID_M = 5000
DEFAULT_ZONE_FAR_M = 20000

MIN_GRACE_WINDOW_S = 60
MAX_GRACE_WINDOW_S = 3600
MIN_RESYNC_SILENCE_S = 60
MAX_RESYNC_SILENCE_S = 3600
MIN_RESYNC_HOLD_S = 0
MAX_RESYNC_HOLD_S = 300
MAX_DEBOUNCE_S = 60

STATIONARY_THRESHOLD_FACTOR = 0.15
STATIONARY_THRESHOLD_MIN_M = 15.0

# Minimum elapsed seconds between _calc_pair calls to credit zone/proximity buckets.
# Guards against rapid-fire recalculates (real GPS bursts or debounce=0 back-to-back
# events) where near-zero _elapsed_s would silently leak time into today_unaccounted.
MIN_CALC_ELAPSED_S = 0.1

DIRECTION_APPROACHING = "approaching"
DIRECTION_DIVERGING = "diverging"
DIRECTION_STATIONARY = "stationary"
DIRECTIONS = [DIRECTION_APPROACHING, DIRECTION_DIVERGING, DIRECTION_STATIONARY]

BUCKET_VERY_NEAR = "very_near"
BUCKET_NEAR = "near"
BUCKET_MID = "mid"
BUCKET_FAR = "far"
BUCKET_VERY_FAR = "very_far"
BUCKETS = [BUCKET_VERY_NEAR, BUCKET_NEAR, BUCKET_MID, BUCKET_FAR, BUCKET_VERY_FAR]

# Altitude
ALTITUDE_MIN_M = -500.0
ALTITUDE_MAX_M = 15000.0
CONF_ALTITUDE_ALIGNED_THRESHOLD_M = "altitude_aligned_threshold_m"
DEFAULT_ALTITUDE_ALIGNED_THRESHOLD_M = 5.0
MIN_ALTITUDE_ALIGNED_THRESHOLD_M = 0.0
MAX_ALTITUDE_ALIGNED_THRESHOLD_M = 100.0
